### ISSUE TITLE
Scripts (like run_shell.sh) do not work on Windows

### ISSUE THREAD

**Issue by amkhare** [bslatkin/dpxdt#112]
I am new to python and need help in resolving issue I am getting.
i am trying to execute run_shell.sh on windows 7 64bit machine using git bash.
when I run the ./run_shell.sh script I keep getting errors

$ ./run_shell.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "dpxdt\__init__.py", line 19, in <module>
    import gflags
  File "c:\Users\username\Downloads\dpxdt-0.1\dpxdt-0.1\dependencies\lib\gflags.py", line 1
    ../python-gflags/gflags.py
    ^
SyntaxError: invalid syntax

the settings in common.sh are 
#!/bin/bash

export PYTHONPATH=.:./dependencies/lib:$PYTHONPATH
export CAPTURE_SCRIPT=dpxdt/client/capture.js

export PHANTOMJS_BINARY=phantomjs

export RELEASE_SERVER_PREFIX=http://localhost:5000/api
export QUEUE_SERVER_PREFIX=http://localhost:5000/api/work_queue

export PHANTOMJS_DEPLOY_BINARY=phantomjs

I added phantomjs in environment variables

please help me on this

**Comment by renuc** [comment]
Any luck getting this to work on windows?

**Comment by bslatkin** [comment]
With #145 this should be a lot better because it's using virtualenv now. [See the documentation](https://virtualenv.pypa.io/en/latest/userguide.html#activate-script) for details.

**Comment by bslatkin** [comment]
This should now be fixed because of d08f74c
