### ISSUE TITLE
Failed after max attempts: CaptureFailedError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ocastillo** [bslatkin/dpxdt#120]
Hello,

I've installed dpxdt, ran the initial test run with:

./run_url_pair_diff.sh \
    --upload_build_id=1 \
    http://www.google.com \
    http://www.yahoo.com

It returns:

Creating release 2014-11-21 14:11:23.111688
Requesting captures
Marking runs as complete
Results viewable at: http://localhost:5000/release?id=1&name=2014-11-21+14%3A11%3A23.111688&number=1

But I get an error "Needs retry: CaptureFailedError: [Errno 2] No such file or directory":

![dpxdt_fail](https://cloud.githubusercontent.com/assets/917864/5143497/3279ec78-7156-11e4-8ac7-5a9dc387f56f.png)

Do I need to change permissions on a directory somewhere?

Thanks in advance.

**Comment by bslatkin** [comment]
Sorry for the delay. Do you have phantomjs installed properly? My guess is that's your problem.

**Comment by bslatkin** [comment]
I added some double-checks in 6fe0d173e29e5319d3a34b3903ecfd703306f96e
