### ISSUE TITLE
Failed after max attempts: CaptureFailedError: returncode=127 

### ISSUE THREAD

**Issue by madmaniak** [bslatkin/dpxdt#124]
My test run is failing with this message. What does it mean?

**Comment by bslatkin** [comment]
Sorry for the delay!

This probably means that running PhantomJS failed for some reason. I found this:

"Value 127 is returned by /bin/sh when the given command is not found "

Do you have PhantomJS installed and available on the correct path? I'd check the server logs to see what exact path it's using.

I'm going to close this for now but please reopen if you're not able to resolve the issue now.
