### ISSUE TITLE
Option to set an acceptable tolerance for image diffs

### ISSUE THREAD

**Issue by scrofts** [bslatkin/dpxdt#130]
Sometimes it's expected that a page will change a little from day to day, for example if the page displays the date. Currently using dpxdt to diff a page like that isn't ideal because it will always show a diff has failed and you need to check this manually. It would be great if there was a config option to allow you to set an acceptable diff % value so that dpxdt marks anything with a diff of less than that % as a success.

**Comment by bslatkin** [comment]
It's really hard to know if those percentages are false positives or real changes though, right?

One idea: Is it possible to inject CSS into the page to cause those areas that change often to be `visibility:  hidden` or something similar? That will give you a stable diff and cause the areas that change to be left out of the actually diffed pixels.

**Comment by scrofts** [comment]
That seems like it's probably a better idea. Thanks.
