### ISSUE TITLE
Update to PhantomJS 2

### ISSUE THREAD

**Issue by danvk** [bslatkin/dpxdt#132]
It's here! http://phantomjs.org/release-2.0.html

This update includes several years' worth of browser improvements, including support for things like web fonts and styling of UI widgets.

**Comment by danvk** [comment]
Unclear what "update" means here since dpxdt doesn't include an explicit dependency on Phantom. Maybe just "verify that it works with PhantomJS2"?

**Comment by bslatkin** [comment]
Yeah I think that's all it is. :)

**Comment by pitchandtone** [comment]
Subscribe

**Comment by danvk** [comment]
I just ran `site_diff.py` w/ a local server on my Mac using [PhantomJS2][1]. It made a mysterious `Failed after max attempts: CaptureFailedError: Sent SIGKILL to item=dpxdt.client.capture_worker.CaptureWorkflow` error which I think had something to do with TypeKit go away.

@bslatkin unless you have any objections, this is safe to close!

[1]: https://github.com/eugene1g/phantomjs/releases/tag/2.0.0-bin

**Comment by bslatkin** [comment]
Awesome. Do we need to update the instructions to say install PhantomJS 2? Or are we good? I've got some general changes to the README coming in my virtual_env branch so I can mention we're using Phantom 2 in there.

**Comment by danvk** [comment]
The version I linked to is a fork that runs on OS X Yosemite. So long as users can get a copy of phantomjs2 that runs on their machine, dpxdt should just work.
