### ISSUE TITLE
How to ignore multiple prefixes on a site diff (crawl)

### ISSUE THREAD

**Issue by olivierbouwman** [bslatkin/dpxdt#136]
I'm trying to ignore multiple prefixes for a site diff (crawl) but having no luck. Am I doing it wrong or does it not support multiple prefixes yet? I tried a lot of different ways of combining two urls in the command line but none worked for me. One prefix works great.

Command line option example:
./run_site_diff.sh --upload_build_id=4 --crawl_depth=-1 --ignore_prefixes='http://www.test.com/test1,http://www.test.com/test2' "http://www.test.com"

Relevant source code:
https://github.com/bslatkin/dpxdt/blob/0295b385de75bccb4680dbc33b0f2dadf12ee0d8/dpxdt/tools/site_diff.py#L210

**Comment by bslatkin** [comment]
The separator is spaces (like CSS classes), so you should do:

./run_site_diff.sh --upload_build_id=4 --crawl_depth=-1 --ignore_prefixes='http://www.test.com/test1 http://www.test.com/test2' "http://www.test.com"

Please reopen if that doesn't work.
