### ISSUE TITLE
git submodule update --init --recursive  fails

### ISSUE THREAD

**Issue by vickikozel** [bslatkin/dpxdt#138]
with this output:

git submodule update --init --recursive
fatal: reference is not a tree: 5300c576deb2f2c60535af2d89b82d10ab443fa4
Unable to checkout '5300c576deb2f2c60535af2d89b82d10ab443fa4' in submodule path 'dependencies/flask-mail'

**Comment by Acubed** [comment]
I'm seeing this too. Maybe flask-mail rebased their repository?

Workaround: `cd dependencies/flask-mail && git checkout master`

**Comment by vickikozel** [comment]
yes, this is what I did too. But we are using these calls as part of automation, so it'd be great if there was a real fix. Thank you for your response.

**Comment by elsigh** [comment]
Yup, I just found this too.

**Comment by bslatkin** [comment]
I'm going to take my branch of flask-mail out of the dependencies because they're not going to accept my patch <https://github.com/mattupstate/flask-mail/pull/44>. We'll need to find a different way to send mail on App Engine, which is fine.

**Comment by bslatkin** [comment]
Trying to fix in #143

**Comment by bslatkin** [comment]
Fixed
