### ISSUE TITLE
pending resources causes fail

### ISSUE THREAD

**Issue by bryanrasmussen** [bslatkin/dpxdt#139]
I have a lot of fails in my build, like the following
  Run failed
Needs retry: CaptureFailedError: Sent SIGKILL to item=dpxdt.client.capture_worker.CaptureWorkflow({args: ('/v

based apparently on a couple of resources never loading / always being pending - example from log below

2015-04-06T12:06:17 [DEBUG] WebPage - updateLoadingProgress: 100 
page.onLoadFinished
Loaded the page successfully
Finished loading page: http://localhost/products w/ status: success
2015-04-06T12:06:17 [DEBUG] WebPage - setupFrame "" 
Status of all resources: {"done":69,"pending":2}
Still waiting for: http://localhost/templates/prod_product_search_result.ejs

I'm not sure why these are having problems, they are loading and being rendered in the page itself, but even if they aren't shouldn't there just be a screenshot taken given that the page finished loading with status success. 

Is there anyway to ignore the pending resources?

**Comment by bslatkin** [comment]
Yes you can use `resourcesToIgnore` to filter out those resources that you don't want to even load.

See how this is used here: <https://github.com/bslatkin/dpxdt/blob/master/dpxdt/client/capture.js#L88>

Please reopen this issue if that doesn't work for you!
