### ISSUE TITLE
You can't login to non-default versions on App Engine

### ISSUE THREAD

**Issue by bslatkin** [bslatkin/dpxdt#148]
If you're trying to test out a new version before setting it live, you can't login. My guess is the cause is that the hostnames are different (https://version-dot-yourapp.appspot.com vs. https://yourapp.appspot.com). The cookie gets set on .yourapp.appspot.com, so the auth doesn't carry over in either direction. Pretty dumb. Maybe we could add an auth redirector that lets you set the cookie cross domain or something?

**Comment by elsigh** [comment]
This seems like a GAE-deployment issue and is currently kinda irrelevant.
