### ISSUE TITLE
Help README clarifications

### ISSUE THREAD

**Issue by dave-r12** [bslatkin/dpxdt#151]
Not sure if this is the right place for this, but am interested in learning more about this and had a few questions on the README:

* Workflow related - For applications that use forms, would the expected workflow likely be the 'Diff My Images'? Am thinking we need to drive our app with selenium, and save screenshots after submission, does that sound right?
* I'm struggling with the notion of releases, the README says, "Each release may be attempted many times". I realize this is intended for continuous delivery, but if we release once a week would we have only 1 release for the week with likely many builds for that release? For example, every commit triggers a build for that release

**Comment by bslatkin** [comment]
For workflow: You can inject JS to drive the UI, fill in forms, etc. You use JS and DOM functions to trigger the events you need to test. See <https://github.com/bslatkin/dpxdt#configuration>

For the releases: Sorry that's confusing. A "build" is really just a project. Within a project you have multiple attempts for a single release. Each of those release attempts has a number of test runs to verify if the current release attempt is good. So you can expect 1 project, 1 "approved" release per week, but multiple attempts per approved release corresponding to each new compilation/build of your program (which is triggered by a commit).

Hope that helps!

**Comment by dave-r12** [comment]
Got it - thanks Brett
