### ISSUE TITLE
Suggestion for new fields for Release model (user_who_changed_status, notes)

### ISSUE THREAD

**Issue by elsigh** [bslatkin/dpxdt#152]
It would be cool to see the username of the person who marked a Release as Good or Bad.

It would also be cool to be able to append a notes field to a Release (e.g. changelist notes) so it would be obvious to someone looking at a diff that a given change was intended (or not).

If you like either of these ideas, I'm happy to take these on.

**Comment by bslatkin** [comment]
Did you see the admin logs or audit logs at the bottom of a build? I have the info recorded there. Is that good enough?

I agree being able to specify notes per release would be good. The current system has the release URL which is supposed to be a catch all for this. My thinking was it would point at a bug tracker or some better system for managing notes and coordinating about release status.

**Comment by elsigh** [comment]
All good then. I didn't notice the logs. Just to clarify you mean the "release_cut_url" flag yeah?

**Comment by bslatkin** [comment]
Yep release_cut_url is the one! If that's not good enough we can add notes, but lemme know if that's okay?

**Comment by elsigh** [comment]
Cool - it's just at the bottom of the page, so I never saw it before.
Could we move it to the top to be under the release name?

For the audit log, I'd love to surface the username inline next to Good/Bad to be like:
Good by elsigh

In my case I include the person who pushed to our production branch in the release name so I'd like to see their matching signoff on the release. (this may be too specific to my use case though)

Too much?

**Comment by bslatkin** [comment]
Moving some links up sounds good. I just stuffed them down there because why not. If you've got a better place to put them I'm all for it.

Showing the last username to touch a release makes sense to me. I think you can query for it from the admin logs with a join, instead of denormalizing it.
