### ISSUE TITLE
Running ./run_site_diff.sh throws 'AttributeError: verbose_workers'

### ISSUE THREAD

**Issue by jaredgilmore** [bslatkin/dpxdt#169]
Trying to run the following to test out dpxdt:
`./run_site_diff.sh \
    --upload_build_id=1 \
    --crawl_depth=1 \
    http://www.google.com`
Throws the following error:
`dpxdt (master) $ ./run_site_diff.sh     --upload_build_id=1     --crawl_depth=1     http://www.google.com
Traceback (most recent call last):
  File "./dpxdt/tools/site_diff.py", line 369, in <module>
    main(sys.argv)
  File "./dpxdt/tools/site_diff.py", line 358, in main
    if FLAGS.verbose_workers:
  File "/usr/local/lib/python2.7/site-packages/gflags.py", line 1059, in __getattr__
    raise AttributeError(name)
AttributeError: verbose_workers`

Am I missing a dependency or is something not installed correctly? I've been following the documentation and I am not sure what the issue may be. Running other scripts like run_site_diff.sh works just fine. 

Any help is appreciated. Thank you.

**Comment by jaredgilmore** [comment]
Looks like I was missing symlinks for my Python install.

Running: `brew link --overwrite python` fixed this issue!

**Comment by sypets** [comment]
Or when using the installation instructions from Brett (https://github.com/bslatkin/dpxdt#depicted-server), make sure you are using the correct python environment (created by virtualenv):

`which python`
(should be the local bin/python)

if not, probably call this in your current shell:
`source bin/activate`
