### ISSUE TITLE
Remove running attempts from queue

### ISSUE THREAD

**Issue by NicoHaase** [bslatkin/dpxdt#176]
It would be cool to remove a whole attempt from the workers queue. If you start an attempt covering a lot of URLs and immediatly find an error, you could save a lot of time if this option was available

**Comment by bslatkin** [comment]
Sorry for my delay. This behavior is somewhat present here:

https://github.com/bslatkin/dpxdt/blob/master/dpxdt/server/api.py#L130

If the last attempt is still processing when the next one is kicked off, the API will automatically cancel all tasks for the last release before starting the next one.

Is that what you meant? If not, could you reopen and clarify? Thanks!
