### ISSUE TITLE
Auth issues creating diffs when using OAuth

### ISSUE THREAD

**Issue by weeksghost** [bslatkin/dpxdt#187]
Hello,

I have followed the instructions relating to deployment https://github.com/bslatkin/dpxdt#deployment

After successfully running the server and authenticating, when I run a diff against my API server a few things happen (but) no run is fully executed (see screenshot below). Meaning, a release run is created but a diff never occurs and remains "pending" unless I the `--ignore_auth` flag  to the run_server at which point diffs will run as normal.

Below are some details:

**Server flags**
```--port=5000
--enable_api_server
--enable_queue_workers
--fetch_use_internal_redirects
--release_server_prefix=http://localhost:5000/api
--queue_server_prefix=http://localhost:5000/api/work_queue
--fetch_frequency=10
--fetch_threads=10
--capture_threads=10
--capture_wait_seconds=2
--phantomjs_timeout=20
--queue_idle_poll_seconds=30
--queue_busy_poll_seconds=1
--pdiff_threads=10
--pdiff_wait_seconds=2
--pdiff_timeout=20
--polltime=1
```

**Entry from Server log**
```
DEBUG auth.py:274] API request lacks authorization header
INFO _internal.py:87] 127.0.0.1 - - [29/Jul/2016 19:31:30] "POST /api/work_queue/run-pdiff/lease HTTP/1.1" 401
```

**Release page**

![cursor_and_tester_ _auth__2](https://cloud.githubusercontent.com/assets/2256604/17261092/1b8c8bd8-55a2-11e6-8e93-40b3a914776e.png)

**What I have tried**

- Verified my oauth credentials
- Verified my `settings.cfg`
- Verified my `server/config.py`

Any insight will be greatly appreciated.

Thank you.

**Comment by bslatkin** [comment]
Did you set the `--release_client_id` and `--release_client_secret` flags? On the project you need to go to the "API Keys" page and configure keys for your command-line client or workers. Please reopen this issue if that doesn't fix it!
