### ISSUE TITLE
Do tools exist to configure tests (including JS) for dpxdt?

### ISSUE THREAD

**Issue by rileylark** [bslatkin/dpxdt#61]
The sitediff tool seems to create a bunch of new runs (TEST run, not release run?) on the fly by crawling URLs.  Is there a tool that can read a directory of tests or a yaml / json config file, instead of crawling a site?  Is there any tool that can associate a given JS file with a test?

If these tools don't exist, would you be interested in a pull request with such a tool?

---

That's my main set of questions.  I've also taken some time to write up my current understanding of dpxdt and a confusion re. `request_run`.  Normally I'd edit it out of the issue but it may be useful, if you have the time to read it, in understanding my state of mind and the confusions a developer might have coming to the project.

I've just started to explore dpxdt and it looks very useful. I got the sitediff tool up and running and... wow, what a great resource!

Unfortunately, a lot of our app is heavily dependent on JS interactions.  I see APIs for injecting JS in a release, but I would need to inject different JS for each test run.  It looks like client/capture.js just runs one test at a time, accepting a bit of injected JS at the per-test level, but the API only accepts injectJs for `request_run`, which runs the whole set of tests for the whole release candidate(?).

[10 minutes of code-reading pass]

Now I see that SiteDiff makes a new RequestRunWorkflow, which calls `/request_run`, so maybe request_run is really just running a single test and not a whole release?  That is counter to my understanding from the guide:

> Requests a new run for a release candidate. Causes the API system to take screenshots and do pdiffs. When ref_url and ref_config are supplied, the system will run two sets of captures (one for the baseline, one for the new release) and then compare them.

**Comment by mcampster** [comment]
Did anything ever become of this (dpxdt-client)? I already have a load of functional tests written in protractor, and would love to be able to simply send screenshots to dpxdt and let it handle comparison/workflow. 

The closest I have found is VisualReview but this only supports taking whole screenshots, not partial. Ideally, I would use protractor pixx-diff plugin to take the screenshots, and then dpxdt-client to send it to dpxdt for comparisson to baseline and workflow.
