### ISSUE TITLE
Discussion / question: Image processing workers on AppEngine

### ISSUE THREAD

**Issue by rileylark** [bslatkin/dpxdt#80]
Hey Brett,

I'm interested in the possibility of using AppEngine for image processing - bursting up to lots of parallel processors and then coming back down to zero is intriguing!

I plan on making a javascript API client (#61) this week, but wonder if you have any thoughts on the feasibility of running the image processing workers in the form of task queue tasks. Do you know of any image processing libraries that will work on AppEngine? Maybe docker support would enable some? If you have any leads, and/or think this would be a valuable addition, I think I can work on this this month.

**Comment by bslatkin** [comment]
Alright you can now run the image workers on App Engine using Managed VMs. This is merged into head with #145.

**Comment by rileylark** [comment]
Wow, awesome!
