### ISSUE TITLE
run_combined.sh crashes after about a day

### ISSUE THREAD

**Issue by joseph-connolly** [bslatkin/dpxdt#83]
I love this tool. I'm running into some stability issues and don't know where to look for the cause. I'm using run_combined.sh and find that the process crashes about once a day. I have also had the app stop running with a database error. Can you tell me where to look so I can provide a more detailed error log?

**Comment by mhemesath** [comment]
I've also noticed the app continuously crashes. I haven't had time to look into the cause though.

**Comment by bslatkin** [comment]
Thanks for the report @joseph-connolly and sorry for the delay in responding. I was pretty confused when I saw this and wasn't sure how to debug. I see a similar report in issue #128 that makes me think there's more to this.

Do you remember what the stack track is when the program crashes? I assume you're using SQLite right?

**Comment by thxmike** [comment]
We also see this issue. We ended up using Upstart to keep the service up when it fails. However, it would be nice to find out what the cause is. We are running ubuntu 12.02

**Comment by bslatkin** [comment]
@thxmike Are you using ./run_combined.sh directly? I think the culprit may be the `--reload_code` flag. What we need is a script that starts the whole stack in "production mode".

**Comment by bslatkin** [comment]
My other idea is the default database location is:

```
SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/test.db'
```

And something on your system is blowing the file away. I can reproduce the `sqlalchemy.exc.OperationalError` exception just by running `rm /tmp/test.db` while the server is up.

**Comment by bslatkin** [comment]
Okay I think I fixed this in 1f401220ccbd712dd63becffd24b468614cf97e2. Check out these instructions:

https://github.com/bslatkin/dpxdt#sqlite-instance

Let me know if that fixes the issue! This should also make it easy to deploy dpxdt to a VM.
