### ISSUE TITLE
How to handle user logins?

### ISSUE THREAD

**Issue by bryanrasmussen** [bslatkin/dpxdt#89]
The site I am testing needs the user to be logged in with Google's openid, or it redirects to the login page. 
Is there a way to handle this with dpxdt?

**Comment by bslatkin** [comment]
All that's left to do here is to add this to the FAQ

**Comment by bslatkin** [comment]
I added the cookies list to the config documentation. I haven't found the time to expand the docs much. It seems like people are figuring this out so I'm going to close.
